variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - lint

gitleaks:
  stage: lint
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.18.2-mega-1.0
    entrypoint: [""]
  script:
    - gitleaks detect -v --redact -c .gitleaks/gitleaks.toml

clang-format:
  stage: lint
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y git clang-format
  script: |
    COMMITS=$(git log --pretty=format:%H origin/$CI_DEFAULT_BRANCH..HEAD)

    for COMMIT in $COMMITS
    do
        OUTPUT=$(git -c color.ui=always clang-format --diff $COMMIT^ $COMMIT)

        printf '%s\n' "$COMMIT"

        if [ -z "$OUTPUT" ]
        then
            continue
        fi

        if echo $OUTPUT | grep -q 'no modified files to format'
        then
            continue
        fi

        if echo $OUTPUT | grep -q 'clang-format did not modify any files'
        then
            continue
        fi

        printf '%s\n' "$OUTPUT"
        exit 1
    done
